default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: buytickets-app_development

test:
  <<: *default
  database: buytickets-app_test
  
production:
  <<: *default
  database: buytickets-app_production
  username: buytickets-app
  password: <%= ENV['BUYTICKETS-APP_DATABASE_PASSWORD'] %>
